#!/usr/bin/bash

if  [ $1 == '-h' ]
then
    echo "./del_users [user1] [user2] ..."
    exit 0
fi


for user in $@
do
    sudo userdel $user
    sudo rm /var/mail/$user -rf
    sudo rm /home/$user -rf
    sudo rm /d/home/$user -rf
    echo "- [$user] is deleted."
done

